RABBIT_MQ_HOST: 10.1.1.63
RABBIT_MQ_PORT: 5672
EUREKA_HOST: 10.1.1.63
MYSQL_HOST: 10.1.1.63

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/service4crowd_engine?useUnicode=true&characterEncoding=UTF8
    username: root
    password: 1706223
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  jackson:
    serialization:
      indent_output: true
  activiti:
    check-process-definitions:  false
  application:
    name: service-workflow
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port:  ${RABBIT_MQ_PORT:5672}
    username: guest
    password: guest

eureka:
    instance:
        statusPageUrlPath: /info
        healthCheckUrlPath: /health
        # docker 部署开启
        prefer-ip-address: true
        # ip-address: 10.1.1.63
        instance-id: ${spring.cloud.client.ip-address}:${server.port}
    client:
        serviceUrl:
            defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/

server:
  port: 8092

auth:
  serviceId: server-auth
  user:
    token-header: Authorization
  client:
    token-header: client-token
    id: service-workflow
    secret: GK4POfgK

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 120000
  ConnectTimeout: 120000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false