EUREKA_HOST: 10.1.1.62
EUREKA_PORT: 8761
RABBITMQ_HOST: localhost
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/workflow
    username: root
    password: 1706223
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    serialization:
      indent_output: true
  activiti:
    check-process-definitions:  false
  application:
    name: service-workflow
  rabbitmq:
    host: ${RABBITMQ_HOST}
    username: ldkobe
    password: 1706223
    port: 5672
    virtual-host: /


eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/

server:
  port: 8090

auth:
  serviceId: server-auth
  user:
    token-header: Authorization
  client:
    token-header: client-token
    id: service-workflow
    secret: qIhsTUOF


ribbon:
  eureka:
    enabled: true
  ReadTimeout: 120000
  ConnectTimeout: 120000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false