EUREKA_HOST: 10.1.1.63
server:
  port: 8761
eureka:
  instance:
    hostname: ${EUREKA_HOST:localhost}
  client:
    # 表示是否将自己注册到Eureka Server，默认为true。由于当前这个应用就是Eureka Server，故而设为false
    registerWithEureka: false
    # 表示是否从Eureka Server获取注册信息，默认为true。因为这是一个单点的Eureka Server，不需要同步其他的Eureka Server节点的数据，故而设为false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${server.port}/eureka/

spring:
  application:
    name: eureka-server