RABBIT_MQ_HOST: 10.1.1.63
RABBIT_MQ_PORT: 5672
EUREKA_HOST: 10.1.1.63
MONGO_HOST: 10.1.1.63
spring:
  data:
    mongodb:
      uri: mongodb://crowd:1706223@${MONGO_HOST:localhost}:27017/CrowdData
  application:
    name: service-data-core
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    username: guest
    password: guest
    port: ${RABBIT_MQ_PORT:5672}
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB
eureka:
    instance:
        statusPageUrlPath: /info
        healthCheckUrlPath: /health
        # docker 部署开启
        prefer-ip-address: true
        # ip-address: 10.1.1.63
        instance-id: ${spring.cloud.client.ip-address}:${server.port}
    client:
        serviceUrl:
            defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/

server:
  port: 8807


auth:
  serviceId: server-auth
  user:
    token-header: Authorization
  client:
    token-header: client-token
    id: service-data-core
    secret: XpJan8vc
hadoop:
  hdfs:
    uri: hdfs://10.1.1.62:8020
    user: root


