EUREKA_HOST: 10.1.1.62
RABBITMQ_HOST: 192.168.3.131
spring:
  data:
    mongodb:
      uri: mongodb://crowd:1706223@localhost:27017/CrowdData
  application:
    name: service-data-core
  rabbitmq:
    host: ${RABBITMQ_HOST}
    username: ldkobe
    password: 1706223
    port: 5672
    virtual-host: /
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/

server:
  port: 8800


auth:
  serviceId: server-auth
  user:
    token-header: Authorization
  client:
    token-header: client-token
    id: service-data-core
    secret: GVVzzZiJ


