RABBIT_MQ_HOST: 10.1.1.63
RABBIT_MQ_PORT: 5673
EUREKA_HOST: 10.1.1.63
server:
  port: 8027

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/

spring:
  application:
    name: service-model-detection
  data:
    mongodb:
      uri: mongodb://crowd_fastwash:1706223@10.1.1.63:27017/fastwash
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port:  ${RABBIT_MQ_PORT:5672}
    username: guest
    password: guest
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB

auth:
  user:
    token-header: Authorization
  client:
    token-header: client-token
    id: service-model-detection
    secret: ShOriSwn

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 120000  #设置路由转发请求的超时时间，是对请求连接建立之后的处理时间
  ConnectTimeout: 120000 #路由转发请求时候，创建请求连接的超时时间，如果小于timeoutInMilliseconds会自动进行重试路由请求
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false


hystrix:
  threadpool:
    default:
      coreSize: 1000 #并发执行的最大线程数，默认10
      maxQueueSize: 1000 #BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 #即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000000  #API网关中路由转发请求的HystrixCommand执行超时时间，为毫秒。超过Hystrix会将该执行命令标记为Timeout并标记为异常
          strategy: SEMAPHORE