RABBIT_MQ_HOST: 10.1.1.63
RABBIT_MQ_PORT: 5672
EUREKA_HOST: 10.1.1.63
MYSQL_HOST: 10.1.1.63
REDIS_HOST: 10.1.1.63
MONGO_HOST: 10.1.1.63
APP_HOST: 10.1.1.62
eureka:
    instance:
        statusPageUrlPath: /info
        healthCheckUrlPath: /health
        # docker 部署开启
        prefer-ip-address: true
        # ip-address: 10.1.1.63
        instance-id: ${spring.cloud.client.ip-address}:${server.port}
    client:
        serviceUrl:
            defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
server:
    port: 8503
spring:
    application:
        name: service-manage
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    datasource:
        name: test
        url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/service4crowd?useUnicode=true&characterEncoding=UTF8
        username: root
        password: 1706223
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    data:
      web:
        pageable:
          default-page-size: 20
     ## 当前页参数名 默认为 page
          page-parameter: page
     ## 当前页参数名 默认为 size
          size-parameter: size
     ## 字段排序参数名 默认为 sort
          # sort-parameter: orderBy 不起作用
      mongodb:
         uri: mongodb://crowd:1706223@${MONGO_HOST:localhost}:27017/CrowdData
    servlet:
      multipart:
        max-file-size: 2048MB
        max-request-size: 2048MB
    rabbitmq:
        host: ${RABBIT_MQ_HOST:localhost}
        port:  ${RABBIT_MQ_PORT:5672}
        username: guest
        password: guest
# 必须配置
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 120000
  ConnectTimeout: 120000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false

hystrix:
  threadpool:
    default:
      coreSize: 1000 ##并发执行的最大线程数，默认10
      maxQueueSize: 1000 ##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 110000
swagger:
    enabled: true
    base-package: cn.edu.buaa.act.auth.center
    title: auth-center
    version: 1.0.0.SNAPSHOT
    description: 认证服务
    contact:
        name: admin

auth:
  serviceId: service-manage
  user:
    token-header: Authorization
  client:
    token-header: client-token
    id: service-manage
    secret: qTDrnSaD
storage:
  dest: /home/LAB/wusj/service4crowd/service


