RABBIT_MQ_HOST: 10.1.1.63
RABBIT_MQ_PORT: 5673
EUREKA_HOST: 10.1.1.63
MYSQL_HOST: 10.1.1.63
REDIS_HOST: 10.1.1.63
server:
    port: 8762
spring:
    application:
        name: auth-center
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    datasource:
        name: test
        url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/service4crowd?useUnicode=true&characterEncoding=UTF8
        username: root
        password: 1706223
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
#        name: auth
#        type: com.alibaba.druid.pool.DruidDataSource
#        filters: stat
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/service4crowd?useUnicode=true&characterEncoding=UTF8
#        username: root
#        password: 1706223
#        initialSize: 1
#        minIdle: 1
#        maxActive: 20
#        maxWait: 60000
#        #间隔多久进行一次检测，检测需要关闭的空闲连接
#        timeBetweenEvictionRunsMillis: 60000
#        #一个连接在池中最小生存的时间
#        minEvictableIdleTimeMillis: 300000
#        validationQuery: select 'x'
#        testWhileIdle: true
#        testOnBorrow: false
#        testOnReturn: false
#        #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
#        poolPreparedStatements: true
#        maxOpenPreparedStatements: 20
#        # druid:

    #redis-cache 相关
    redis:
        pool:
            maxActive: 300
            maxIdle: 100
            maxWait: 1000
        host: ${REDIS_HOST:localhost}
        port:  ${REDIS_PORT:6379}
        password:
        timeout: 2000
        # 服务或应用名
        sysName: auth-center
        enable: true
        database: 0
    rabbitmq:
        host: ${RABBIT_MQ_HOST:localhost}
        port:  ${RABBIT_MQ_PORT:5672}
        username: guest
        password: guest
#  zipkin:
#    #内存方式配置，不需要
#    #base-url: http://localhost:9411
#    #日志发送队列类型
#    sender:
#      type: rabbit
#    #发送的队列名称，默认zipkin，正常情况不要修改因为zipkin-server默认监控队列也是zipkin
#    rabbitmq:
#      queue: zipkin
    sleuth:
  #统计收集百分比默认0.1，正式环境可不配置
      sampler:
        percentage: 1.0

mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: cn.edu.buaa.act.auth.center.model
#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check


eureka:
    instance:
        statusPageUrlPath: /info
        healthCheckUrlPath: /health
        # docker 部署开启
        prefer-ip-address: true
        ip-address: 127.0.0.1
    client:
        serviceUrl:
            defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
# 必须配置
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 120000
  ConnectTimeout: 120000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false

hystrix:
  threadpool:
    default:
      coreSize: 1000 ##并发执行的最大线程数，默认10
      maxQueueSize: 1000 ##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 110000
swagger:
    enabled: true
    base-package: cn.edu.buaa.act.auth.center
    title: auth-center
    version: 1.0.0.SNAPSHOT
    description: 认证服务
    contact:
        name: admin

auth:
  serviceId: auth-center
  user:
    token-header: Authorization



jwt:
  token-header: Authorization
  expire: 14400
  rsa-secret: xx1WET12^%3^(WE45

