spring:
    application:
        name: server-trace
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
    virtual-host: /
server:
    port: 8759 #启动端口

eureka:
     instance:
        preferIpAddress: true
        statusPageUrlPath: /actuator/info
        healthCheckUrlPath: /actuator/health
     client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/
