EUREKA_HOST: 10.1.1.62
server:
    port: 8504
eureka:
#    instance:
#        statusPageUrlPath: /info
#        healthCheckUrlPath: /health
#        # docker 部署开启
#        prefer-ip-address: true
#        ip-address: 127.0.0.1
    client:
        serviceUrl:
            defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
spring:
    application:
        name: service-mlflow
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
     ## 是否显示 SQL 语句
    datasource:
        name: test
        url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/service4crowd_mlflow?useUnicode=true&characterEncoding=UTF8
        username: root
        password: 1706223
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
    data:
      web:
        pageable:
          default-page-size: 20
     ## 当前页参数名 默认为 page
          page-parameter: page
     ## 当前页参数名 默认为 size
          size-parameter: size
     ## 字段排序参数名 默认为 sort
          sort-parameter: orderBy
    servlet:
      multipart:
        max-file-size: 2048MB
        max-request-size: 2048MB
    rabbitmq:
      host: localhost
      username: guest
      password: guest
      port: 5672
      virtual-host: /
mlflow:
    trackingUri: http://192.168.3.188:5000
ftp:
    host: 192.168.3.117

auth:
  serviceId: service-mlflow
  user:
    token-header: Authorization
  client:
    token-header: client-token
    id: service-mlflow
    secret: qTDrnSaD