
server:
  port: 8001

hadoop:
  hdfs:
    uri: hdfs://192.168.3.219:9000
    user: root

spring:
  application:
    name: service-hadoop
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB